name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

      steps:
     - name: Checkout code
       uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/u957777877/public_html
            git pull origin production
            composer install --no-dev
            php artisan migrate
            php artisan config:cache
            php artisan route:cache
            php artisan optimize
