name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Deploy to Hostinger
      run: |
        sudo apt-get install -y sshpass
                sshpass -p "" ssh "${{ secrets.USERNAME }}"@hostname "cd //home/u957777877/public_html && git pull origin main && php artisan migrate --force"

        # sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${secrets.USERNAME}@${{ secrets.HOST }} "cd //home/u957777877/public_html && git pull origin main && php artisan migrate --force"
